[toolchain]

[features]
resolution = false
skip-lint = false

[programs.mainnet]
intent = "FgPgECEpBRdV9gV18jR7icvpPabEvgVJof3A6aPn1UjY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
